<?php
/** @var \MageSuite\GuestWishlist\Model\ViewModel\CopyWishlistLink $viewModel */
$viewModel = $block->getViewModel();
$guestWishlist = $viewModel->getGuestWishlist();
?>
<div class="cs-dashboard__wishlist-guest">
    <span class="cs-dashboard__wishlist-guest-label"><?=__('To recreate this wishlist in other browsers please use following link')?>:</span>
    <code class="cs-dashboard__wishlist-guest-code">
        <?=$viewModel->getCopyLink()?>
    </code>
</div>